version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: fleetfalcon_db
    restart: always
    environment:
      - POSTGRES_USER=ff_user
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=ff_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: